---
- hosts: all
  become: yes
  gather_facts: yes
  vars:
    regex: '[^A-Za-z0-9._-]'
    replace: '_'

  vars_files:
    - vars/default.yml

  roles:
    - docker

  tasks:
  - name: Ensure Nvidia GPU role if enabled
    import_role:
      name: gpu
    when: enable_nvidia_gpu is defined and enable_nvidia_gpu

  - name: Ensure rDocker role
    import_role:
      name: rDocker

  - name: Verify all Traefik endpoints are accessible
    uri:
      url: http://{{ item.key }}.{{ docker_domain }}
      status_code: 200,302,401,403
      validate_certs: no
    with_dict:
      - "{{ docker_container_map }}"
    when:
      - item.value.traefik is defined and item.value.traefik
      - item.value.enabled is defined and item.value.enabled
      - docker_container_map['traefik']['enabled'] is defined and docker_container_map['traefik']['enabled']
      - traefik_verify_endpoints is defined and traefik_verify_endpoints
