---
- name: Generate Docker and Traefik configurations
  hosts: all
  become: yes
  vars:
    regex: '[^A-Za-z0-9._-]'
    replace: '_'

  vars_files:
    - roles/rautomate/defaults/main.yml
    - vars/default.yml

  tasks:
    - name: Ensure rautomate_ docker_data_path exists
      ansible.builtin.file:
        path: "{{ rautomate_docker_data_path }}"
        state: directory
        mode: 0775

    - name: Ensure Traefik config.
      ansible.builtin.template:
        src: roles/rautomate/templates/traefik.yml.j2
        dest: "{{ rautomate_docker_data_path }}/traefik.yml"
        mode: 0644

    - name: Ensure docker-compose.yml file.
      ansible.builtin.template:
        src: roles/rautomate/templates/docker-compose.yml.j2
        dest: "{{ rautomate_docker_data_path }}/docker-compose.yml"
        group: docker
        mode: 0775
        backup: yes
