---
services: {{ rautomate_docker_container_map }}
services_restart_policy: {{ rautomate_container_restart_policy }}
services_container_expose_ports: {{ rautomate_container_expose_ports }}
services_container_enable_auto_updates: {{ rautomate_container_enable_auto_updates }}
services_container_auto_update_schedule: {{ rautomate_container_auto_update_schedule }}
services_docker_apps_path: {{ rautomate_docker_apps_path }}
services_project_name: {{ rautomate_project_name }}
services_service_name: {{ rautomate_service_name }}
