---
- name: Ensure platform agnostic requirements are installed.
  set_fact:
    docker_platform_agnostic_requirements_state: present
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Ensure platform agnostic requirements are installed.
  set_fact:
    docker_platform_agnostic_requirements_state: latest
  when: ansible_distribution in ['CentOS', 'Fedora', 'RedHat']

- name: Install Docker with convenience script
  ansible.builtin.script: "curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh"
  args:
    creates: /usr/bin/docker
  register: docker_install
