---
- name: Ensure previous RHEL Docker packages are absent.
  ansible.builtin.package:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent

- name: Ensure RHEL required packages.
  ansible.builtin.package:
    name:
      - epel-release
    state: "{{ docker_prereq_packages_state }}"

- name: Ensure CentOS requirements.
  when:
    - distribution_override == "centos"
  block:
    - name: Ensure yum-utils.
      ansible.builtin.package:
        name: yum-utils
        state: "{{ docker_prereq_packages_state }}"

- name: Ensure Fedora requirements.
  when:
    - ansible_facts['distribution'] | lower == "fedora"
  block:
    - name: Ensure previous Fedora Docker packages are absent.
      ansible.builtin.package:
        name:
          - docker-selinux
          - docker-engine-selinux
        state: absent

    - name: Ensure Fedora dnf-plugins-core.
      ansible.builtin.package:
        name: dnf-plugins-core
        state: "{{ docker_prereq_packages_state }}"

- name: Ensure RHEL Docker repo.
  ansible.builtin.yum_repository:
    name: docker-ce-stable
    description: "Docker CE Stable - $basearch"
    baseurl: https://download.docker.com/linux/{{ distribution_override | lower }}/$releasever/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/{{ distribution_override | lower }}/gpg
    state: "{{ docker_repo_state }}"

