name: Ansible Lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4.3.1
      with:
        python-version: 3.9.16
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible ansible-lint
    - name: Lint playbook
      run: |
        ansible-lint -v *.yml
        ansible-playbook -i hosts --syntax-check *.yml