# This is a basic workflow to help you get started with Actions

name: Ansible Lint Check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  lint-check:
    name: Ansible lint check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.3.1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint
      - name: Lint playbook
        run: |
          ansible-lint -v *.yml
          ansible-playbook --inventory inventory --connection local --syntax-check *.yml
    # steps:
    #   - uses: actions/checkout@v3
    #   - name: Ansible Lint
    #     uses: ansible/ansible-lint-action@v6.8.2
    #     with:
    #       path: "./"

