# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  lint-check:
    name: Ansible lint check
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      # You may pin to the exact commit or the version.
      # uses: sudosubin/git-clone-action@8a93ce24d47782e30077508cccacf8a05a891bae
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        # Repository owner and name. Ex: sudosubin/git-clone-action
        #repository: # optional, default is ${{ github.repository }}
        # Git host platform. Ex: github, gitlab, bitbucket, gitee, or else (git.suckless.org, ...)
        #platform: # optional, default is github
        # Git branch or tag to checkout.
        ref: master
        # Relative path from current directory, where to clone.
        path: .
    - name: Ansible Lint
      uses: ansible/ansible-lint-action@v6.8.2
      with:
        path: "./"
    
