name: Test Builds

on:
  workflow_call:

jobs:
  build-matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        version: [3.9.16, 3.10.9, 3.11.1]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Check ${{ matrix.os }} compatibility w/ py-v${{ matrix.version }}
        uses: actions/setup-python@v4.3.1
        with:
          python-version: ${{ matrix.version }}
      - name: Install Ansible dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint
      - name: Check Ansible-Playbook local docker.yml
        run: |
          ansible-playbook -i inventory --connection local docker.yml
      - name: Upload docker compose as artifact
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: Build artifact
          path: /opt/rAutomate/docker-compose.yml
