name: Test Builds

on:
  workflow_call:

jobs:
  build-matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        version: [3.9.16, 3.10.9, 3.11.1]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build out ${{ matrix.os }} / py-v${{ matrix.version }}
        uses: actions/setup-python@v4.3.1
        with:
          python-version: ${{ matrix.version }}
      - name: Install Ansible dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint
      - name: Run Ansible-Playbook local docker.yml
        run: |
          ansible-playbook -i inventory --connection local docker.yml
      - name: Upload docker compose as artifact
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: Build artifact
          path: /opt/rAutomate/docker-compose.yml
      - name: Generate Network Diagram
        if: ${{ success() }}
        run: |
          git clone https://github.com/LeoVerto/docker-network-graph.git
          cd docker-network-graph
          pipenv install
          pipenv run python docker-net-graph.py -o ~/output.svg
      - name: Upload Network Diagram
        uses: actions/upload-artifact@v3
        with:
          name: Generated Network Diagram Artifact
          path: ~/output.svg

