# This is a basic workflow to help you get started with Actions

name: C/I

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  lint:
    name: Ansible Playbook lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.3.1
        with:
          python-version: 3.8.15
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint
      - name: Lint playbook
        run: |
          ansible-lint -v *.yml
          ansible-playbook --inventory inventory --connection local --syntax-check *.yml
  check:
    name: Check OS and Python Compatibility
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, ubuntu-18.04, macos-12, macos-11, macos-10.15]
        version: [3.8.15, 3.9.16, 3.10.9, 3.11.1]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Check ${{ matrix.os }} compatibility with Python v${{ matrix.version }}
        uses: actions/setup-python@v4.3.1
        with:
          python-version: ${{ matrix.version }}
      - name: Install Ansible dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint
      - name: Check Ansible-Playbook local docker.yml
        run: |
          ansible-playbook -i inventory --connection local docker.yml --check  
    
