name: Network Diagram w/ GraphViz

on:
  workflow_run:
    workflows: ["C/I"]
    types: [requested]
    branches: 
      - 'master'
      
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
- uses: actions/checkout@v3
      with:
        node-version: '20.x'
    - name: Install Python 3.9
      uses: actions/setup-python@v4.3.1
      with:
        node-version: '20.x'
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get install graphviz
        python -m pip install --upgrade pip
        pip install ansible ansible-lint pipenv graphviz docker pydot
    - name: Run Ansible-Playbook local docker.yml
      run: |
        ansible-playbook -i inventory --connection local docker.yml
    - name: Generate Network Diagram
      if: ${{ success() }}
      run: |
        git clone https://github.com/LeoVerto/docker-network-graph.git
        cd docker-network-graph
        pipenv install
        pipenv run python docker-net-graph.py -o ~/output.svg
    - name: Upload Network Diagram
      uses: actions/upload-artifact@v3
      with:
        name: Generated Network Diagram Artifact
        path: ~/output.svg
