name: 'Dev: Ansible Playbook Check'

on:
  workflow_call:

jobs:
  dev_branch_check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4.3.1
      with:
        python-version: 3.11.1
    - name: Install Ansible dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible
    - name: Run ansible-playbook check on site.yml
      run: |
        ansible-playbook -i hosts site.yml --check
    name: Check on on latest ubuntu, python, and ansible
