---
- name: Run RHEL-based install.
  ansible.builtin.import_tasks: redhat.yml
  when: family_override | lower == "redhat"

- name: Run Debian-based install.
  ansible.builtin.import_tasks: debian.yml
  when: ansible_facts["os_family"] | lower == "debian"

- name: Verify nvidia-container-runtime-hook is in $PATH
  ansible.builtin.command: "which nvidia-container-runtime-hook"
  register: nvidia_container_runtime_hook_path
  changed_when: nvidia_container_runtime_hook_path in $PATH

- name: Exit if nvidia-container-runtime-hook is not in $PATH
  ansible.builtin.fail:
    msg: "nvidia-container-runtime-hook not found in $PATH"
  when: nvidia_container_runtime_hook_path.rc != 0

- name: Ensure the nvidia-docker2 package
  ansible.builtin.package:
    name: nvidia-docker2
    state: "{{ gpu_prereq_packages_state }}"
  notify:
    - restart docker

- name: Verify CUDA container works
  ansible.builtin.command:
    cmd: "docker run --name nvidia-gpu-test --rm --gpus all nvidia/cuda:11.0-base nvidia-smi"
  register: nvidia_gpu_test
  changed_when: nvidia_gpu_test == False

- name: Exit if CUDA container fails
  ansible.builtin.fail:
    msg: "CUDA container failed to run"
  when: nvidia_gpu_test.rc != 0
