---
- name: Obtain public IP.
  community.general.net_tools.ipify_facts:
  register: public_ip

- name: Ensure paths exists locally.
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ rDocker_docker_data_path }}"
    - "{{ rDocker_docker_apps_path }}"
    - "{{ rDocker_docker_mount_path }}"
    - "{{ rDocker_docker_media_path }}"

- name: NAS base configuration tasks.
  ansible.builtin.include_tasks: "nas_{{ rDocker_docker_media_share_type | lower }}.yml"

- name: Ensure additional NAS configuration
  ansible.builtin.include_tasks: "nas_additional_{{ item.type | lower }}.yml"
  with_items: "{{ rDocker_nas_client_remote_additional_paths }}"
  when:
    - nas_client_remote_additional_paths is defined
    - nas_client_use_additional_paths is defined and nas_client_use_additional_paths
  no_log: yes

- name: Ensure library folders.
  ansible.builtin.file:
    path: "{{ rDocker_docker_media_path }}/{{ item.folder_name }}"
    state: directory
  with_items: "{{ rDocker_docker_library_folders }}"

- name: Ensure container config directories exist.
  ansible.builtin.file:
    path: "{{ rDocker_docker_apps_path }}/{{ item.key }}/config"
    state: directory
  with_dict: "{{ rDocker_docker_container_map }}"
  when: item.value.directory and (item.value.enabled is defined and item.value.enabled)

- name: Ensure Traefik
  ansible.builtin.import_tasks: "traefik.yml"
  when: rDocker_docker_container_map.traefik.enabled is defined and rDocker_docker_container_map.traefik.enabled

- name: Ensure docker-compose.yml file.
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ rDocker_docker_data_path }}/docker-compose.yml"
    group: docker
    mode: 0775
    backup: yes

- name: Ensure containers defined in compose file.
  community.docker.docker_compose:
    project_src: "{{ rDocker_docker_data_path }}"
    project_name: "{{ rDocker_project_name }}"
    pull: "{{ rDocker_container_pull_images_first }}"
    state: "{{ rDocker_docker_compose_container_state }}"
    remove_orphans: "{{ rDocker_container_remove_orphans }}"
  when: not ansible_check_mode

- name: Ensure Transmission and VPN connection
  ansible.builtin.import_tasks: "transmission.yml"
  when: rDocker_docker_container_map.transmission.enabled is defined and rDocker_docker_container_map.transmission.enabled
