---
- name: Wait for VPN init
  ansible.builtin.command: sleep 15
  changed_when: False

- name: Get public IP from Transmission VPN container.
  ansible.builtin.command: docker exec transmission curl -s icanhazip.com
  register: vpn_public_ip
  changed_when: false

- name: Ensure public IP and transmission VPN public IP are different.
  when: ansible_facts['ipify_public_ip'] != vpn_public_ip.stdout
  ansible.builtin.debug:
    msg:
      - Your public IP is protected!
      - "Current public IP: {{ ansible_facts['ipify_public_ip'] }}"
      - "Current VPN IP: {{ vpn_public_ip.stdout }}"

- name: Public IP and VPN IP are identical, stop container
  when: ansible_facts['ipify_public_ip'] == vpn_public_ip.stdout
  block:
    - name: Stop transmission if public IP and VPN IP are identical.
      ansible.builtin.command: docker stop transmission

    - name: Print error message if public IP and VPN IP are identical.
      ansible.builtin.debug:
        msg:
          - Your public IP is NOT protected!
          - "Current public IP: {{ ansible_facts['ipify_public_ip'] }}"
          - "Current VPN IP: {{ vpn_public_ip.stdout }}"
          - The Transmission container has been stopped
  changed_when: false